name: "Multi event pipeline / workflow" #Name of the pipeline

on:
    push: #Event : Whenever a push is made to the repository on the main branch
        branches:
            - main

    pull_request: # Event: Whenever a pull request is made to the repository
        branches:
            - main
jobs:
    on-push: #Name of Job 1
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on main push" #Step 1
              run: echo "Running on the MAIN push" #Step 2

    
    on-pull-request: #Name of Job 2
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pulling from main" 
              run: echo "Running cause pulled from main"


















